name: Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://npm.pkg.github.com'
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Publish the application
        run: |
          echo '***************************************************'
          echo '***************************************************'
          echo '** WORKFLOW CALL...'
          echo '***************************************************'
          echo '***************************************************'
          npm run publish
          echo '***************************************************'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
